version: "3.8"

services:
  mariadb:
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
    networks:
      - inception
#   service2:
#     build:
#       context: .
#       dockerfile: ./srcs/service2/Dockerfile
#     networks:
#       - inception
#   service3:
#     build:
#       context: .
#       dockerfile: ./srcs/service3/Dockerfile
#     networks:
#       - inception
networks:
  inception: