version: "3.8"

services:
  mariadb:
    build:
      context: ./requirements/mariadb/Dockerfile
    networks:
      - inception
  nginx:
    build:
      context: ./requirements/nginx/Dockerfile
    networks:
      - inception
  wordpress:
    build:
      context: ./requirements/wordpress/Dockerfile
    networks:
      - inception
networks:
  inception: