version:  "3.9"

services:

  mariadb:
    container_name: mariadb
    restart:  always
    build:
      context:  ./requirements/mariadb/
    networks:
      - inception

  nginx:
    container_name: nginx
    restart:  always
    build:
      context:  ./requirements/nginx/
    networks:
      - inception

  wordpress:
    container_name: wordpress
    restart:  always
    build:
      context:  ./requirements/wordpress/
    networks:
      - inception

networks:
  inception: