version: "3.8"

services:
  mariadb:
    build:
      context: ./requirements/mariadb/
    networks:
      - inception
  nginx:
    build:
      context: ./requirements/nginx/
    networks:
      - inception
  wordpress:
    build:
      context: ./requirements/wordpress/
    networks:
      - inception
networks:
  inception: