version:  "3.9"

networks:
# --------------Network------------- #
  inception:

volumes:
# --------------Volumes------------- #
  DB:
    name: DB
    driver: local
    driver_opts:
      type: none
      device: '/Users/arnaud/home/${USER}/data/DB'
      o: bind

  WordPress:
    name: WordPress
    driver: local
    driver_opts:
      type: none
      device: '/Users/arnaud/home/${USER}/data/WordPress'
      o: bind

services:
# --------------MariaDB------------- #
  mariadb:
    image: mariadb:myVersion
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    volumes:
      - DB:/var/lib/mysql
    networks:
      - inception
    ports:
      - 3306
    restart:  always

# ---------------NginX-------------- #
  nginx:
    image: nginx:myVersion
    container_name: nginx
    build:
      context: ./requirements/nginx
    networks:
      - inception
    ports:
      - 443
      - 9000
    restart:  always
    depends_on:
      - wordpress

# -------------Wordpress------------ #
  wordpress:
    image: wordpress:myVersion
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_HOST
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception
    ports:
      - 3306
      - 9000
    depends_on:
      - mariadb
    # restart:  always