version:  "3.9"

services:

  mariadb:
    container_name: mariadb
    # restart:  always
    build: requirements/mariadb/
    image: mariadb
    networks:
      - inception

  nginx:
    container_name: nginx
    # restart:  always
    build: requirements/nginx/
    image: nginx
    networks:
      - inception

  wordpress:
    container_name: wordpress
    # restart:  always
    build: requirements/wordpress/
    image: wordpress
    networks:
      - inception
    

networks:
  inception: